name: run Lmod tests
on: [push, pull_request]

jobs:
  Lmod_tests:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest]
          luaVersion: ["5.1"]
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install dependencies MacOS
        if: matrix.os == 'macos-latest'
        run: brew install coreutils gnu-sed
      - name: install dependencies Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install tcsh tcl tcl-dev uuid r-base r-base-dev cmake fish tclsh zsh ksh
      - name: set up lua
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - name: install luarocks
        uses: leafo/gh-actions-luarocks@v4.0.0
      - name: install lua dependencies
        run: |
          luarocks install luaposix
          luarocks install luafileSystem
          luarocks install luajson
          luarocks install lua-term
          luarocks install busted
      - name: set up Hermes
        run: |
         cd /tmp
         git clone https://github.com/rtmclay/Hermes.git
         echo "$PWD/Hermes/bin" >> $GITHUB_PATH
         cd -
      - name: Lmod_test_suite
        run: |
         mkdir b0
         cd b0
         ../configure --prefix=/tmp
         make install
         cd -
         cd /tmp
         git clone https://github.com/rtmclay/Lmod_test_suite.git
         cd -
         cd /tmp/Lmod_test_suite
         .   /tmp/lmod/lmod/init/profile ; tm -k normal
         cd -
         
        
